Museum attendance data preparation for Avila Adobe.  
Portfolio-cleaned notebook for loading, validating, and saving monthly visitor data.

#1 Setup Environment, Load Libraries and Load Raw CSV

In [1]:
# importing necessary libraries
import pandas as pd
from pathlib import Path

# setting up directories for raw and processed data
RAW_DIR = Path("../data/raw/museum")
PROCESSED_DIR = Path("../data/processed")

# creating directories if they don't exist
RAW_DIR.mkdir(parents=True, exist_ok=True)
PROCESSED_DIR.mkdir(parents=True, exist_ok=True)

# defining file paths for raw and processed data
raw_file = RAW_DIR / "avila_adobe_monthly_raw.csv"
processed_file = PROCESSED_DIR / "museum_monthly.csv"

# reading the raw data file into a pandas DataFrame
df = pd.read_csv(raw_file)
df.head()

        month  year  month_number       museum  visitors  covid_period
0  2014-01-01  2014             1  Avila Adobe     24778             0
1  2014-02-01  2014             2  Avila Adobe     18976             0
2  2014-03-01  2014             3  Avila Adobe     25231             0
3  2014-04-01  2014             4  Avila Adobe     26989             0
4  2014-05-01  2014             5  Avila Adobe     36883             0

#2 Inspect the Columns

In [2]:
# displaying the columns and shape of the DataFrame
print(df.columns.tolist())
print(df.shape)
df.head()

['month', 'year', 'month_number', 'museum', 'visitors', 'covid_period']
(90, 6)

        month  year  month_number       museum  visitors  covid_period
0  2014-01-01  2014             1  Avila Adobe     24778             0
1  2014-02-01  2014             2  Avila Adobe     18976             0
2  2014-03-01  2014             3  Avila Adobe     25231             0
3  2014-04-01  2014             4  Avila Adobe     26989             0
4  2014-05-01  2014             5  Avila Adobe     36883             0

#3 Fix the Month Format and Columns Kept

In [4]:
# converting the 'month' column to datetime format and then back to string format in "YYYY-MM" format
df["month"] = pd.to_datetime(df["month"]).dt.strftime("%Y-%m")
df.head()

     month  year  month_number       museum  visitors  covid_period
0  2014-01  2014             1  Avila Adobe     24778             0
1  2014-02  2014             2  Avila Adobe     18976             0
2  2014-03  2014             3  Avila Adobe     25231             0
3  2014-04  2014             4  Avila Adobe     26989             0
4  2014-05  2014             5  Avila Adobe     36883             0

In [5]:
# creating a new DataFrame with only the 'month' and 'visitors' columns for further analysis
museum = df[["month", "visitors"]].copy()
museum.head()

     month  visitors
0  2014-01     24778
1  2014-02     18976
2  2014-03     25231
3  2014-04     26989
4  2014-05     36883

#4 Check for Duplicate Months and Missing Values

In [6]:
# checking for duplicate months, missing values, and the number of rows in the DataFrame
print("Duplicate months:", museum["month"].duplicated().sum())
print("\nMissing values:")
print(museum.isna().sum())
print("\nRows:", len(museum))

Duplicate months: 0

Missing values:
month       0
visitors    0
dtype: int64

Rows: 90

#5 Sort by Month

In [7]:
# sorting the DataFrame by the 'month' column and resetting the index
museum = museum.sort_values("month").reset_index(drop=True)
museum.head()

     month  visitors
0  2014-01     24778
1  2014-02     18976
2  2014-03     25231
3  2014-04     26989
4  2014-05     36883

#6 Save the Processed File

In [8]:
# saving the processed DataFrame to a new CSV file in the processed data directory
museum.to_csv(processed_file, index=False)
print(f"Saved processed museum file to: {processed_file}")

Saved processed museum file to: ../data/processed/museum_monthly.csv

In [9]:
print(museum.head(12))
print(museum.columns.tolist())
print(museum.tail())

      month  visitors
0   2014-01     24778
1   2014-02     18976
2   2014-03     25231
3   2014-04     26989
4   2014-05     36883
5   2014-06     29487
6   2014-07     32378
7   2014-08     37680
8   2014-09     28473
9   2014-10     27995
10  2014-11     25691
11  2014-12     18754
['month', 'visitors']
      month  visitors
85  2021-02         0
86  2021-03         0
87  2021-04         0
88  2021-05         0
89  2021-06      3710